name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t spring-app .

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

#      - name: Push Docker image to Railway
#        env:
#          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
#        run: |
#          docker tag spring-app registry.railway.app/2f0017fe-730f-48dd-8aa0-9da2b50d587f/web
#          docker push registry.railway.app/2f0017fe-730f-48dd-8aa0-9da2b50d587f/web

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up
